# Generated by Django 5.1.6 on 2025-02-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_course_discount_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='school',
            name='discount_time',
        ),
    ]
