# Generated by Django 5.1.6 on 2025-02-19 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentEn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='CommentRu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pay_later', models.DecimalField(decimal_places=2, max_digits=15)),
                ('after_course', models.TextField()),
                ('discount', models.IntegerField()),
                ('discount_place', models.IntegerField()),
                ('image', models.ImageField(default='courses/course_python.jpg', upload_to='courses/')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pay_later', models.DecimalField(decimal_places=2, max_digits=15)),
                ('after_course', models.TextField()),
                ('discount', models.IntegerField()),
                ('discount_place', models.IntegerField()),
                ('image', models.ImageField(default='courses/course_python.jpg', upload_to='courses/')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('discount', models.IntegerField()),
                ('discount_place', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolRu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('discount', models.IntegerField()),
                ('discount_place', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherEn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
